### ISSUE TITLE
High CPU use (low performance)

### ISSUE THREAD

**Issue by jfestrada** [huwwp/cryptop#21]
I didn't review the code but the CPU is highly used by python3 when the script is running. 

Br

**Comment by jfestrada** [comment]
I've solved it just adding time.sleep(60) in the main loop. 

![image](https://user-images.githubusercontent.com/7290345/28780816-62524c56-7608-11e7-8dc5-73263a181184.png)

**Comment by juanjux** [comment]
#22 Should fix this if merged

**Comment by jfestrada** [comment]
Maybe a good idea could be update the data asynchronous and update the screen every 30 seconds, also should be a good idea to show a count down.

Br

**Comment by juanjux** [comment]
@jfestrada the PR actually updates the data asynchronously (using threading.Timer instead of async, easier than a loop just for this but eventually the program could benefit from an event loop once more features are added). I also tried to update the screen in that same thread and it works (probably because of the GIL) so I left it that way, trough updating just the data and then retrieving that and updating the interface on the main thread would be better (but not simpler).

**Comment by huwwp** [comment]
Reopened as the PR had issues with terminal resizing, will look more into it when I get a chance

**Comment by huwwp** [comment]
Latest build runs under 1% cpu usage in most situations for me, jumps to about 2.5% during requests, let me know how it goes

**Comment by jfestrada** [comment]
I've tested it and i can confirm that the latest build barely use the CPU.
